version: "3.9"

services:
  postgres_viral:
    image: postgres:latest
    container_name: postgres-viral
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    command: ["postgres", "-c", "max_connections=250"]
    ports:
      - "5433:5432"
    volumes:
      - postgres_viral_data:/var/lib/postgresql/18/main

volumes:
  postgres_viral_data:
